name: soiltrack_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.3
  toastification: ^2.3.0
  http: ^1.3.0
  permission_handler: ^10.0.0
  wifi_scan: ^0.4.1+1
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  fl_chart: ^0.69.0
  wifi_iot: ^0.3.19+1
  network_info_plus: ^6.1.3
  connectivity_plus: ^6.1.3
  geolocator: ^13.0.2
  crypto: ^3.0.6
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.5.1
  mqtt_client: ^10.5.1
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    #LIST OF LOGO
    - assets/logo/DARK HORIZONTAL.png
    - assets/logo/DARK VERTICAL.png
    - assets/logo/LIGHT HORIZONTAL.png
    - assets/logo/LIGHT VERTICAL.png
    - assets/logo/GREEN OUTLINE.png
    - assets/logo/soiltrack main.png
    - assets/logo/soiltrack gradient.png

    #ELEMENTS
    - assets/elements/microchip.png
    - assets/elements/handphone.png

    #SOIL PICTURES
    - assets/soil_images/clay_soil.png
    - assets/soil_images/loam_soil.png
    - assets/soil_images/sandy_soil.png

    #BACKGROUND
    - assets/background/first_container.png
    - assets/background/projectBg.png
    - assets/background/background_splash.png

    #WEATHER WIDGETS
    - assets/weather/night.png
    - assets/weather/normal_night.png
