name: soiltrack_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^17.0.0

  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.3
  toastification: ^2.3.0
  http: ^1.3.0
  permission_handler: ^10.0.0
  wifi_scan: ^0.4.1+1
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  fl_chart: ^0.69.0
  wifi_iot: ^0.3.19+1
  network_info_plus: ^6.1.3
  connectivity_plus: ^6.1.3
  geolocator: ^13.0.2
  crypto: ^3.0.6
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.5.1
  mqtt_client: ^10.5.1
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  philippines_rpcmb: ^0.0.3
  app_links: ^6.4.0
  table_calendar: ^3.0.0
  google_generative_ai: ^0.2.2
  image_picker: ^1.0.4
  image: ^3.2.1
  pull_to_refresh_flutter3: ^2.0.2
  dotted_border: ^2.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  turf: ^0.0.10
  day_night_time_picker: ^1.3.1
  duration_picker: ^1.2.0
  lottie: ^3.1.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.7 # Required to generate code
  freezed: ^2.4.7 # Freezed package
  json_serializable: ^6.7.1 # If you want to support JSON serialization

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/model/soil_model.tflite

    #LIST OF LOGO
    - assets/logo/DARK HORIZONTAL.png
    - assets/logo/GREEN OUTLINE.png
    - assets/logo/soiltrack main.png
    - assets/logo/soiltrack gradient.png

    #ELEMENTS
    - assets/elements/microchip.png
    - assets/elements/handphone.png
    - assets/elements/power.png
    - assets/elements/no_power.png
    - assets/elements/sad_icon.png
    - assets/elements/no_notification.png
    - assets/elements/security.png
    - assets/elements/no_ai_reading.png
    - assets/elements/ai_ready.png
    - assets/elements/ai_analysis_screen.png
    - assets/elements/ai_generated.png
    - assets/elements/ai_is_here.png
    - assets/elements/ai_is_here_2.png
    - assets/elements/ai_analysis.png
    - assets/elements/ai_chatbot.png
    - assets/elements/ai_not_found.png
    - assets/elements/ai_weekly_analysis.png
    - assets/elements/soiltrack_loading2.gif

    #SOIL PICTURES
    - assets/soil_images/clay_soil.png
    - assets/soil_images/loam_soil.png
    - assets/soil_images/sandy_soil.png

    #BACKGROUND
    - assets/background/first_container.png
    - assets/background/projectBg.png
    - assets/background/background_splash.png
    - assets/background/get_started.png
    - assets/background/email_verification.png
    - assets/background/ai_background.png
    - assets/background/container_background.png
    - assets/background/container_background_2.png
    - assets/background/container_background_3.png
    - assets/background/mascot_bg.png
    - assets/background/mascot_bg_2.png

    #WEATHER WIDGETS
    - assets/weather/morning.png
    - assets/weather/afternoon.png
    - assets/weather/night.png
    - assets/weather/SUNNY DAY.png
    - assets/weather/CLOUDY DAY.png

    #THUNDER
    - assets/weather/thunder/heavy_thunder_day.png
    - assets/weather/thunder/heavy_thunder_night.png
    - assets/weather/thunder/heavy_thunder_rain_day.png
    - assets/weather/thunder/heavy_thunder_rain_night.png
    - assets/weather/thunder/thunderstorm_day.png
    - assets/weather/thunder/thunderstorm_night.png
    - assets/weather/thunder/thunderstorm_with_rain_day.png
    - assets/weather/thunder/thunderstorm_with_rain_night.png

    #RAIN
    - assets/weather/rain/heavy_rain_day.png
    - assets/weather/rain/heavy_rain_night.png
    - assets/weather/rain/light_rain_day.png
    - assets/weather/rain/light_rain_night.png
    - assets/weather/rain/moderate_rain_day.png
    - assets/weather/rain/moderate_rain_night.png

    #CLOUDY
    - assets/weather/cloudy/cloudy_day.png
    - assets/weather/cloudy/cloudy_night.png
    - assets/weather/cloudy/few_clouds_day.png
    - assets/weather/cloudy/few_clouds_night.png
    - assets/weather/cloudy/overcast_day.png
    - assets/weather/cloudy/overcast_night.png

    #CLEAR
    - assets/weather/clear/clear.png
    - assets/weather/clear/normal_night.png

    #HARDWARE
    - assets/hardware/nano_colored.png
    - assets/hardware/nano_not_connected.png
    - assets/hardware/esp_colored.png
    - assets/hardware/esp_not_connected.png
    - assets/hardware/esp32_with_shadow.png
    - assets/hardware/esp_not_connected_with_shadow.png
    - assets/hardware/nano_not_connected_with_shadow.png
    - assets/hardware/nano_with_shadow.png
    - assets/hardware/moisture_colored.png
    - assets/hardware/npk_colored.png
    - assets/hardware/waterpump_connected.png
    - assets/hardware/valves.png

    #MASCOTS AI
    - assets/ai_mascot/FIRST.png
    - assets/ai_mascot/SECOND.png
    - assets/ai_mascot/THIRD.png
    - assets/ai_mascot/not_found.png

    #MOVING ELEMENTS
    - assets/elements/No-Data.json
    - assets/elements/no-result.json
    - assets/elements/Live chatbot.json
    - assets/elements/search imm.json
    - assets/elements/checkmark.json
